require_relative 'ruby_onvif_client/path'
require_relative 'ruby_onvif_client/device_management'
require_relative 'ruby_onvif_client/media'
require_relative 'ruby_onvif_client/ptz'
require_relative 'ruby_onvif_client/device_discovery'
